# Netlify configuration for SVMSeek Wallet
[build]
  publish = "build"
  command = "./scripts/build-netlify.sh"

# Production context: All deploys to the main repository branch
[context.production]
  command = "./scripts/build-netlify.sh"
  
[context.master]
  command = "./scripts/build-netlify.sh"

[context.develop]
  command = "./scripts/build-netlify.sh"

# Branch deploy contexts
[context.deploy-preview]
  command = "./scripts/build-netlify.sh"

# SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers for wallet application
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    
    # Content Security Policy for wallet security - relaxed for compatibility
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data: blob:;
      img-src 'self' data: https: blob:;
      connect-src 'self' https: wss: ws: blob: data:;
      worker-src 'self' blob: data:;
      child-src 'self' blob: data:;
      object-src 'none';
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self';
      manifest-src 'self';
      media-src 'self' blob: data:;
    """

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA and extension file handling
[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Handle browser extension files if served
[[redirects]]
  from = "/extension/*"
  to = "/404.html"
  status = 404

# API proxy for development (if needed)
# [[redirects]]
#   from = "/api/*"
#   to = "https://api.mainnet-beta.solana.com/:splat"
#   status = 200
#   force = false